services:
  app:
    build:
      context: .
      platforms:
        - "linux/amd64"
    image: xosothap/visothap-v2
    env_file:
      - .env
    environment:
      # overide only url 
      NEXT_PUBLIC_APP_URL: https://visothap.cloud
